apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: marine-herring-dotnet-basic-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/marine-herring-dotnet-basic-gitops